name: Build

on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push 82
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.php83
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            tuxnvape/multicms:latest
            tuxnvape/multicms:8.2

      #- name: Build and push 82  
       # uses: docker/build-push-action@v3
       # with:
       #   context: .
       #   file: ./Dockerfile.php82
       #   platforms: linux/amd64,linux/arm/v7,linux/arm64
       #   push: true
       #   tags: |
       #     tuxnvape/multicms:8.2
