name: Build

on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push 84  
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.php84
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
              tuxnvape/multicms:8.4

      - name: Build and push 83
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.php83
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            tuxnvape/multicms:8.3
            tuxnvape/multicms:latest

      - name: Build and push 82  
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.php82
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            tuxnvape/multicms:8.2
